### ISSUE TITLE
Configurable Timeout

### ISSUE THREAD

**Issue by geekdave** [admc/wd#249]
I'm testing a web app that's oftentimes slow to respond due to high network latency.  So I need a fairly high timeout (10 sec or more) in my `waitForXYZ` calls.

I'd prefer to set this through a global configuration instead of passing a parameter on every `waitForXYZ` call.

What's the preferred way to set a global timeout?  [From the looks of it](https://github.com/admc/wd/blob/v0.2.10/lib/webdriver.js#L1148), the "default" values are hardcoded.  Would it be possible to add a configurable default for timeout/pollFreq/retries?

I'd be happy to submit a PR for this if it seems reasonable.  Something along the lines of `wd.configureHttp`, but instead:

```js
wd.configure({
  waitTimeout: 10000,
  waitRetries: 5000,
  waitPollFreq: 300
});

**Comment by sebv** [comment]
Been a long time, has some work been done on this, or can I close?

**Comment by geekdave** [comment]
Unlikely that I'll get a chance to work on this anytime soon, so closing.
