### ISSUE TITLE
File upload crashes PhantomJS (ECONNREFUSED)

### ISSUE THREAD

**Issue by binarykitchen** [admc/wd#303]
After lots of debugging I found that `commands.uploadFile()` crashes PhantomJS somehow along these lines:

```js
    _this._jsonWireCall({
    method: 'POST'
      , relPath: '/file'
      , data: { file: Buffer.concat(dataList).toString('base64') },
      cb: callbackWithData(cb, _this)
    });
```

No clear error message is returned. All I know is that PhantomJS is killed without explanation and the calling code simply throws a ECONNREFUSED:

```
{ [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```

I'd like to see more info and want to understand why the file upload is not working.

PS: I am calling `sendKeys()` in my E2E test script which is calling `commands.uploadFile()`.

**Comment by sebv** [comment]
Another phantomJs issue.
