### ISSUE TITLE
console.log() output with logs(type, cb);

### ISSUE THREAD

**Issue by malandrew** [admc/wd#329]
When I execute remote javascript using the `execute()` method, like so:

```
browser.execute('console.log("foo");', function(err, results) {
    if (err) return console.log(err);
    browser.log('browser', function(err, logsArr) {
         if (err) return console.log(err);
         console.log(logsArr); // returns [];
    });
}
```

The logs array is always empty. However if I instead use `console.info`, `console.warn` or `console.error` the logsArr does not come back empty. Since I'm trying to capture TAP test output written to the console, this is blocking me since passing tests, plan information and comments are all written using `console.log`. 

Also, under what conditions are `client` and `server` log types returned? Currently, only `browser` and `driver` log types are returned. 

Lastly, executing `console.log('');` with an empty string appears to result in a log error, whereas a since space does not cause that error `console.log(' ');`. Sometimes TAP tests will write empty strings, so it's important that those empty strings can be handled. Here's the empty string error:

```
[ { level: 'WARNING',
    message: '{"message":{"column":41,"executionContextId":1,"level":"log","line":233,"parameters":[{"type":"string","value":""}],"source":"console-api","stackTrace":[{"columnNumber":41,"functionName":"","lineNumber":233,"scriptId":"26","url":""},{"columnNumber":33,"functionName":"callFunction","lineNumber":222,"scriptId":"26","url":""},{"columnNumber":23,"functionName":"","lineNumber":232,"scriptId":"26","url":""},{"columnNumber":3,"functionName":"","lineNumber":233,"scriptId":"26","url":""},{"columnNumber":39,"functionName":"InjectedScript._evaluateOn","lineNumber":730,"scriptId":"23","url":""},{"columnNumber":52,"functionName":"InjectedScript._evaluateAndWrap","lineNumber":669,"scriptId":"23","url":""},{"columnNumber":21,"functionName":"InjectedScript.evaluate","lineNumber":581,"scriptId":"23","url":""}],"text":"","timestamp":1406662593.96028,"type":"log","url":""}}',
    timestamp: 1406662593961 } ]```

**Comment by sebv** [comment]
Looks like a behavior happening in the javacript client within the browser. You should try to overwrite "console.log" to suit your need (in an earlier execute), we don't really have control over it in the driver.
