### ISSUE TITLE
Unable to manipulate click in IFrame using Android WebDriver

### ISSUE THREAD

**Issue by shlomitc** [admc/wd#355]
## tl;dr
* I test a hybrid app that has an iframe inside a webview.
* Inside the iframe I tried to use `elementById` and `.click()`. It worked on iOS device and emulator but **not on Android**.
* I  worked around it by using `elementByXPath()` and then `tapElement()` (chaining didn't work)
* I am not sure if it's a chromedriver issue or wd's, but for sure I can't chain the tapElement function promise.

## The whole details:
http://stackoverflow.com/questions/26146795/unable-to-manipulate-click-in-iframe-using-android-webdriver/26163233

**Comment by sebv** [comment]
Reopen if needed.
