### ISSUE TITLE
Response Status Code::StaleElementReference(10) && Response Status Code::NoSuchElement(7)

### ISSUE THREAD

**Issue by ColorfullyMe** [admc/wd#356]
Hi, this may be issue related to the ChromeWebDriver itself as some research in Google shows but I am seeking help here too... May be someone knows of a workaround, specially when using **wd**?

Having in mocha test:
```
...
browser
 .get('some URL')
 .elementByCss('#myId')
 .click()
 .eval("window.location.href")
  .should.become('some URL/some_path')
 .notify(done);
...
```
results in Exception:
`Error: [element.click()] Error response status: 10, StaleElementReference - An element command failed because the referenced element is no longer attached to the DOM. Selenium error: stale element reference: element is not attached to the page document`

Some hints show that the DOM is destroyed when `.click()` is invoked thus the reference is lost and becomes stale. Suggested is that the code should wait or make sure the element exists. Something like:
```
...
browser
 .get('some URL')
 .waitForElementByCss(''#myId')
 .elementByCss('#myId')
 .click()
 .eval("window.location.href")
  .should.become('some URL/some_path')
 .notify(done);
...
```
which again results in:
`Error: [elementByCss("'#myId")] Error response status: 7, , NoSuchElement - An element could not be located on the page using the given search parameters. Selenium error: no such element`

So how exactly to implement such behavior?
This is something travail. Clicking a link and running eval on the resulted page. So it should work out of the box but I have a feeling I miss something here!?

Just to mention, that both above snippets work when using **phantomjs** as browser. So it is something related to the ChromeDriver high possibly?

Any help will be appreciated!

**Comment by wjw0970** [comment]
@ColorfullyMe is this issue solved? I encountered the same issue and stocked...
