### ISSUE TITLE
newWindow command creates a new tab instead of a new window in Chrome

### ISSUE THREAD

**Issue by axemclion** [admc/wd#364]
The line at https://github.com/admc/wd/blob/1038c33b0abbe8329d81c9bb6bb62e3df3b440fa/lib/commands.js#L261 creates a new tab instead of a new window. I tested this in Chrome 39. May need to pass a third parameter to actually create a new window, as specified in the docs - https://github.com/admc/wd/blob/1038c33b0abbe8329d81c9bb6bb62e3df3b440fa/doc/api.md#L1521

**Comment by axemclion** [comment]
was curious about why this was closed - is this fixed now ?

**Comment by sebv** [comment]
Too many old issues, cleaning up the backlog. This is not essential, people can just send the javascript to do what they want.

**Comment by axemclion** [comment]
Sounds good, thanks
