### ISSUE TITLE
Please put the API in the README

### ISSUE THREAD

**Issue by nolanlawson** [admc/wd#372]
This is a wonderful library, but it is really overwhelming for newbies, and I am having trouble finding a consistent, single source for accurate API documentation anywhere.

I.e. something that lays out `elementByCss()`, `elementByCssSelector()` (are they different??), `type()` vs `sendKeys()`, etc. would be very helpful.  Thanks!

**Comment by ertrzyiks** [comment]
Im looking for reference here https://github.com/admc/wd/blob/master/doc/api.md then use google/lib code for details.

**Comment by sebv** [comment]
Yeah use:
https://github.com/admc/wd/blob/master/doc/api.md
and
https://code.google.com/p/selenium/wiki/JsonWireProtocol

It'sa very light layer on top of JsonWire, as opposed to the official lib.
