### ISSUE TITLE
How do I wait for an optional element?

### ISSUE THREAD

**Issue by bcherny** [admc/wd#376]
My use case is I hope an element doesn't exist. But if it does, I want to execute a subroutine and continue like normal.

What I have so far:

```js
wd.addPromiseChainMethod('hopeNot', function (selector, cb) {

  var deferred = q.defer(),
      me = this

  this
    .waitForElementByCss(selector, 5000, function (err, element) {

      if (err) {
        return deferred.resolve(me)
      }

      return cb()

    })
    .catch(function(){
      deferred.resolve(me)
    })

  return deferred.promise

})
```

And the consumer:

```js
browser
    .init({
      browserName: 'chrome'
    })
    .get('https:// ...')
    .hopeNot('.selector', function() {
      // handle selector existing
    })
    .waitForElementByCss( ... )
```

Unfortunately, wd exits after #hopeNot instead of continuing to the final #waitForElementByCss. What am I doing wrong?

**Comment by sebv** [comment]
You need to use the default waitFor method, not WaitForElement, then it doesn't matter weather the element is there or not.

**Comment by congthang1** [comment]
I was looking for this and have found this method:


var hopnotFlag = false;

browser
.then (function(){
    return  browser.hasElementByName('hopnotSelector',function(err,flag){
              if (flag) hopnotFlag = True;
      })
})
.then (function(){
   if(hopnotFlag){
      //element exists
        return browser
           .elementByName('hopnotSelector').chooseYourAction()
           .nextAction()

   }else{
      //element is not exists
       return browser
       .doSomAction()
    }
})

**Comment by PombaM** [comment]
did you try hasElementByLocator strategy? it gives a boolean.

**Comment by timneutkens** [comment]
Bumping a really old post, sorry, but wanted to add some context to

> hasElementByLocator strategy

You can find all available `hasElementBy` methods here:

https://github.com/admc/wd/blob/700365d8065a7c8ddd89f4b744c7f7c729d33df4/lib/commands.js#L1236-L1253
