### ISSUE TITLE
Cannot reach an element offscreen

### ISSUE THREAD

**Issue by scgarland191** [admc/wd#382]
There is an element on the webpage I am testing that is not on the screen when the test reaches the page. Attempting to click the element at that point in the test causes it to timeout. However, if I manually scroll down to the element while the script is stuck, the element is successfully clicked.
After seeing this behavior, I attempted to reach the element via the `browser.scroll(xOffset, yOffset)` method, but received the following error: `Selenium error: Underlying driver does not implement advanced user interactions yet`.

Is there a well-known solution to this issue?

Thanks

**Comment by noahtkeller** [comment]
You can use this to scroll the page:

.eval('document.getElementById("yourId").scrollTop = 1000')

**Comment by scgarland191** [comment]
Thanks! That worked perfectly!
