### ISSUE TITLE
TouchAction in promiseChainRemote (appium)

### ISSUE THREAD

**Issue by oriharel** [admc/wd#383]
How to send touch action when using promise chain?
TouchActions needs element. How do I get the element object? to do something like:

it("should get the url", function () {
    
    var action = new wd.TouchAction(driver);
    return driver
        .get('http://ori.il.capriza.com/mobile/maintest.html#devmode#yuval')
        .waitForElementById('tab-header-mc11718', 5000)
        .context('NATIVE_APP')
        .performTouchAction(action.press(el: *element*))
        .context('WEBVIEW_1')
        .waitForElementByCssSelector('#tab-header-mc11718.active', 8000)
        .sleep(2000);
  });

OR: 

it("should get the url", function () {        
        return driver
            .get('http://ori.il.capriza.com/mobile/maintest.html#devmode#yuval')
            .waitForElementByClassName('tabs-container', 5000)
            .context('NATIVE_APP')
            .then(function(*el*) {
                var action = new wd.TouchAction(driver);                
                action.press({el: *e*l})
                    .moveTo({x: 1, y: 0})
                    .wait(200)
                    .release()
                    .perform();

            })
            .then(function(el) {
                driver.context('WEBVIEW_1');
            })
            .waitForElementByCssSelector('#tab-header-mc11718.active', 8000);
    });

Those are imaginary examples as the first one uses 'element' that I'm missing and the second one uses 'el' argument returned in the 'then' and of course that's not true. it's the 'browser' object that is returned.

So how to I get a hold of that desired element and if not, what other options do I have?

Thanks,
Ori

**Comment by sebv** [comment]
There is an example here https://github.com/appium/sample-code/blob/master/sample-code/examples/node/ios-actions.js

**Comment by AndreyMelnichenko** [comment]
@sebv Thanks for link, it was very usefull for me and resolved my case!
