### ISSUE TITLE
How to open link from tool-tip message in Selenium Python?

### ISSUE THREAD

**Issue by arslanbuttar** [admc/wd#387]
What my code is trying to do is to find an then hover on element and a tooltip message is displayed. Click on a link in the tootip message which will take the user to a different page then do some activity there. i have located the element on which tootip message will appear. But I am unable to click on the link which is on tooltip.

**Comment by sebv** [comment]
Doesn't sound like a WD.js bug or issue.

Please go to a selenium discussion group (for instance [here](https://groups.google.com/forum/#!forum/selenium-users)) to ask this kind of questions.
