### ISSUE TITLE
get global variable

### ISSUE THREAD

**Issue by michalmikolajczyk** [admc/wd#392]
Hi, how can I get access to a global variable, which is available from the browser console by e.g.
```
window.angular;
```

I tried 
```
browser.execute('return window.angular', function (err, angular) { 
  // but angular is undefined here
})
```

I also get undefined when trying 
```
browser.execute('return window', ...
```

**Comment by michalmikolajczyk** [comment]
just as a note - I also get undefined when trying 
```
browser.execute('return window', ...
```

**Comment by sebv** [comment]
You can only use this kind of global objects from within the browser, only elements or stuff which can be serialized can be retrieved (but you cannot modify them from the driver, obviously).

There are 2 javascript execution contexts in play here.

**Comment by michalmikolajczyk** [comment]
I don't want to modify, just read. What is the syntax to get it?

I want to execute the command in browser context, then retrieve the value in WD.

It seems strange, the only thing I want to do is well described for other drivers:
http://stackoverflow.com/questions/10455130/can-selenium-web-driver-have-access-to-javascript-global-variables

**Comment by sebv** [comment]
Yeah you can do that. Just check the tests we use $ global variable everywhere https://github.com/admc/wd/blob/master/test/midway/api-exec-specs.js#L56.

**Comment by michalmikolajczyk** [comment]
ok, cool, so it is in fact the function prepareJS, defined here: https://github.com/admc/wd/blob/f49065fa8ff91411f70972f149e90b7f97f4cd39/test/helpers/setup.js#L84

I will try it out, thanks!

**Comment by sebv** [comment]
You only need prepareJS if you use Android and you have carriage returns, which is probably not your case.

**Comment by michalmikolajczyk** [comment]
Thanks for your help! It worked. I guess the problem was, I was mixing execution contexts. When I executed everything in the browser's context, it worked correctly.
