### ISSUE TITLE
Drag and drop in promiseRemote

### ISSUE THREAD

**Issue by hy9be** [admc/wd#394]
A click action in promise without chain is like this: 
```javascript
.then (function () {
    return browser.elementById('someID');
}).then (function (el) { 
    return browser.clickElement(el); 
})
```

What about I want to do a drag and drop action, for which the function has two augments? I stuck at something like this:
```javascript
.then (function () {
    return browser.elementById('someID_1');
}).then (function (el1) { 
    return browser.elementById('someID_2'); 
}).then (function (???)) {
    //???
}
```

**Comment by sebv** [comment]
Q.all

Please read promise doc here: https://github.com/kriskowal/q

**Comment by sebv** [comment]
`Q.all`

Please read promise doc here: https://github.com/kriskowal/q

**Comment by hy9be** [comment]
Thanks! I will give it a try.

**Comment by hy9be** [comment]
@sebv btw, it looks wd does not even have a dnd api according to the document here: https://github.com/admc/wd/blob/master/doc/api.md. Is that a known fact? If it is, then I may need to use the mousedown and mouseup to imitate a dnd?

**Comment by sebv** [comment]
https://github.com/admc/wd/blob/master/examples/promise/drag-n-drop.js

**Comment by sebv** [comment]
There is no Drag and drop api in JsonWire, there no portable way to write it, really it depends on your page.

**Comment by hy9be** [comment]
Got you. Appreciate your help!
