### ISSUE TITLE
Need a way to send common keyboard shortcuts

### ISSUE THREAD

**Issue by lerouxb** [admc/wd#395]
I'm using wd to test a library that uses contenteditable, so I'm trying to send events that are as close to the real thing as possible. Specifically I'm trying to test:

* focus the element
* press cmd-a (ctrl-a) to select all
* press cmd-c (ctrl-c) to copy to clipboard
* move the cursor somewhere
* press cmd-v (ctrl-v) to paste the clipboard contents.
* (the code I'm trying to test would then intercept that event and clean things up)

I've looked it keys() and  I tried browser.keys([wd.SPECIAL_KEYS.Command, 'a']) and various variations but I can't get it to work. I've looked through the examples, tests, issues, the JsonWireProtocol, etc. but it is still not clear to me how to do that.

Is this possible? I just can't get it to work. What am I doing wrong?

**Comment by sebv** [comment]
http://stackoverflow.com/questions/11750447/performing-a-copy-and-paste-with-selenium-2

**Comment by lerouxb** [comment]
I have tried exactly that and it isn't doing anything. Any ideas?

**Comment by lerouxb** [comment]
Actually it sounds like that just doesn't work in OSX:
https://code.google.com/p/chromedriver/issues/detail?id=30

**Comment by sebv** [comment]
Works fine with firefox/yosemite:

https://gist.github.com/sebv/1c638fad003e58a66f72

on OSX you need to use the Meta key, intead of Ctrl.

**Comment by lerouxb** [comment]
I use meta.

Looks like it won't ever work in Chrome on OSX as it is essentially
"wontfix".

Will try Firefox in OSX and Chrome in a Linux VM to get around it.

Pity because contenteditable differs substantially between browsers so
would like to test in all of them, and is especially broken in firefox so
if i drop support for any it would be there..

Works fine with firefox/yosemite:

https://gist.github.com/sebv/1c638fad003e58a66f72

on OSX you need to use the Meta key, intead of Ctrl.

—
Reply to this email directly or view it on GitHub
<https://github.com/admc/wd/issues/395#issuecomment-116744432>.
