### ISSUE TITLE
npm run script doesn't work

### ISSUE THREAD

**Issue by ilanbiala** [admc/wd#398]
Selenium doesn't seem to be the issue, and one of the collaborators says the issue has to do with this package. Is there anything that may be causing the issue?

https://github.com/SeleniumHQ/selenium/issues/794

**Comment by ilanbiala** [comment]
@admc @sebv any ideas as to what's going on?

**Comment by Jonahss** [comment]
I don't think your issue is related to this module at all.

**Comment by ilanbiala** [comment]
So what is if related to if not this and not selenium?

**Comment by sebv** [comment]
Looks like you don't even use the wd package. It's hard to help you, we don't have enough information, there is only little than can be deduced from cut and pasting logs.

**Comment by ilanbiala** [comment]
@sebv is there something environment eise that webdriver needs that when running from npm isn't provided?

**Comment by sebv** [comment]
As I say I suspect you not even using the wd package but the official webdriver package. No need to post on forum like this, just debug your code to see what happens.

**Comment by caoxu2000** [comment]
please see my comment on https://github.com/SeleniumHQ/selenium/issues/794
sebv is right.  you were not using wd package.  you were using webdriver-manager and in your package.json file, you just happen to name the npm script 'wd'
