### ISSUE TITLE
calling driver.quit doesn't seem to quit iOS simulator

### ISSUE THREAD

**Issue by bleonard** [admc/wd#402]
I'm starting a new project using the appium JS library against the iOS simulator.
When I call `driver.quit()` it doesn't seem to work as expected (doesn't close simulator, doesn't register on appium server log)

One thing I noticed is that it does `DELETE /session/:sessionID `
At least that's what the log says.

That seemed odd to me. I would have expected it to be to to an actual session id. Or maybe the logging is just at a higher level. I'm not sure.

But looking at the source, it seems like it might be that this `replace` call is backwards - assuming we wanted to replace `:sessionID` with the_real_ browser session info and not the other way around.

Link to line:
https://github.com/admc/wd/commit/deabac1be143781abf193ce92b9721b1c561a61c#diff-4b29a4950dabaeee1423c8ea22ea8527R15

**Comment by sebv** [comment]
Looks correct to me,we want to hide the session id in logs.

**Comment by bleonard** [comment]
oh, i see. is that code only for logging?

Well then, I have no idea why called `driver.quit()` doesn't shut down the emulator. I would expect to see something in the appium logs that it received a command, but it doesn't receive anything.

**Comment by bleonard** [comment]
well, it seems i was calling the wrong `done()` method. sorry for the trouble.
