### ISSUE TITLE
Q Promises + chaining usage keeps giving "StaleElementReference" or "NoSuchElement" randomly

### ISSUE THREAD

**Issue by jatinder85** [admc/wd#404]
Here is the sample code I am using to follow links which goes to separate pages and I keep getting "StaleElementReference" or "NoSuchElement" on "link2" or "link3" elements.
```
      browser
        .elementByLinkText('i am a link on page 1')
        .click()
        .elementByLinkText('i am a link on page 2')
        .click()
        .elementByLinkText('i am a link on page 3')
        .nodeify(done);
```

Even a modified version with "waitFor" function does not eliminate this issue, I keep getting this error every 2 out of 5 times of running this test.

```
  browser
        .elementByLinkText('i am a link on page 1')
        .click()
        .waitForElementByLinkText('i am a link on page 2')
        .click()
        .waitForElementByLinkText('i am a link on page 3')
        .nodeify(done);
```

Test File: https://gist.github.com/jatinder85/6495f773033e0a8528de

**Comment by jatinder85** [comment]
any update on this?

**Comment by sebv** [comment]
click is asynchronous, you need to wait for conditions on page.
