### ISSUE TITLE
.saveScreenshot() command in saves next interactions

### ISSUE THREAD

**Issue by edoher** [admc/wd#405]
I am using Node.js + Mocha + Grunt + WD.js + Sauce Labs.

I use the .saveScreenshot() command on demand to only take pictures of certain interactions. The problem is that the screenshots saved in my computer are from a later interaction, not the one I want. I made up a workaround by adding some sleep time to wait while the picture is being taken, but this makes the tests very slow and doesn't always work. It would be great to make this function synchronous .

Here is a code example:

```javascript

    it("05 - check: inspiration read more and video", function(done) {
        browser
            .get("http://www.....")
            .elementByXPath('//*[@id="main"]/main/section[4]/div[2]/div[1]')
            .click()
            .saveScreenshot(dir + fileName + '__10 open read more.png')
            .sleep(10000)
            .elementByXPath('//*[@id="main"]/main/section[4]/div[2]/div[1]')
            .click()
            .sleep(2000)
            .get("http://www....")
            .elementByXPath('//*[@id="main"]/main/section[4]/div[2]/article[2]/div/div/div/div')
            .moveTo(100, 100)
            .click()
            .saveScreenshot(dir + fileName + '__11 play video.png')
            .sleep(10000)
            .click()
            .sleep(3000)
            .click()
            .nodeify(done);
    });
```

**Comment by sebv** [comment]
FYI with Node.js, if you don't use sync methods everything is asynchronous.

You can check the code here https://github.com/admc/wd/blob/master/lib/commands.js#L1114-L1142, the method wait until the file has been written before responding. .

The problem in your code is that you call `click` bet don't spin for the results.

**Comment by edoher** [comment]
@sebv  I am aware that Node.js is asynchronous, therefore it would be great if we could have an option to make this method synchronous, so it would stop, take the screenshot, wait until the file is saved and just then move into the next step.

BTW, didn't understand your last comment.

Thanks!

**Comment by sebv** [comment]
It is what the method already does.

**Comment by edoher** [comment]
But why, if I take the .sleep() off, it just goes onto the next steps and makes a screenshot of a few steps forward in the chain instead of pausing while saving the picture?

**Comment by sebv** [comment]
Probably because you don't wait for any condition after `click`.

**Comment by edoher** [comment]
If I make use of the Promise of .saveScreenshot(), should it pause and wait for the result BEFORE doing stuff in the background? Meaning, before moving onto the .click() and so on?

**Comment by sebv** [comment]
Just look at the code here  https://github.com/admc/wd/blob/master/lib/commands.js#L1114-L1142 and put some debug. 

Again: **It is what the method does** (The method callback is inside the writeFile callback.)

If you find a bug please fix it and open a PR.

**Comment by edoher** [comment]
Okay, thanks!

**Comment by krzkaczor** [comment]
I was experiencing weird problems with `saveScreenshot` method and I ended up with rewriting current implementation with custom one using `writeFileSync` and this one works without problems.
