### ISSUE TITLE
How to select a dropdown value?

### ISSUE THREAD

**Issue by mrded** [admc/wd#407]
Hello, 

Can you provide an example, how to select a dropdown value?
Thank you

**Comment by caoxu2000** [comment]
At high level, just treat option values in dropdown as an element to click:
.elementByCss('#state-dropdown option[value="CA"]').click
for regular drop down:
<select id=“state-dropdown”>
	<option value="AL">Alabama</option>
	<option value="AK">Alaska</option>
	<option value="AZ">Arizona</option>
	<option value="AR">Arkansas</option>
	<option value="CA">California</option>
</select>

For select2, it's a bit more challenging.  You can do something like this:
1. click on the main container element of the select2 dropdown
2. do a search using sendKeys
3. do another click on the one that was matching for the search (hope it's unique in the list.  if not then do index)
