### ISSUE TITLE
Feature request debugging capability - similar to protractor

### ISSUE THREAD

**Issue by prolificcoder** [admc/wd#409]
Great framework with a lot of functionality and terseness but sometimes I find myself unable to debug because of the return promise chaining. 

Is there a way to put `debugger;` inside that return statement? Or something like protractor is doing now? https://github.com/angular/protractor/blob/master/lib/protractor.js#L794

**Comment by sebv** [comment]
sounds like node-inspector: https://github.com/node-inspector/node-inspector

**Comment by sebv** [comment]
You can add `.then(function(){ debugger; })` everywhere in the chain.
