### ISSUE TITLE
waitForElementByCss problem or just doing it wrong

### ISSUE THREAD

**Issue by matpol** [admc/wd#410]
This:

` .waitForElementByCss('.tt-dropdown-menu', asserters.isDisplayed, 1000, function(err, el){
                  el.text(function(err, text) { text.should.contain('text here'); });
            })`

passes whatever text I put in the 'text here' string. I am using sauce with chai.

this does what it should but I can't check the text string - am I doing this right?

`.waitForElementByCss('.tt-dropdown-menu', 1000)
            .isDisplayed(function (err, displayed) {  
                assert.equal(displayed, true);
                next(err);
            })`

**Comment by caoxu2000** [comment]
try 
.waitForElementByCss('.tt-dropdown-menu', asserters.isDisplayed, 1000, 200)
.text().then(function (text) { 
      text.should.contain('text here');
      return text;
})
