### ISSUE TITLE
Release notes for v0.4

### ISSUE THREAD

**Issue by MattiSG** [admc/wd#413]
Hi,

You recently released v0.4.0. However, there is no mention of this release in either the [release notes](https://github.com/admc/wd/blob/master/doc/release-notes.md) or [GitHub's releases](https://github.com/admc/wd/releases).

Could you provide us with a list of changes, some of which are probably breaking due to the minor version number update?  :)

Thanks,
Matti

**Comment by MattiSG** [comment]
[Seemingly](https://github.com/admc/wd/compare/8cf5bfeed696e746a6ea1689745bbbef1c34fc6f...a0f356228b9e4ee76f4261bd21c7c316acc88bc9), only wrapping touch actions in an object. Correct?

**Comment by sebv** [comment]
yes, I think multitouch is already wrapped.

**Comment by usmonster** [comment]
If I'm looking at this repo correctly... isn't v0.3.12 more recent than v0.4.0? Was there a reason for this misordered tagging, or was it accidental?

In any case, this is a source of confusion, since even npm is showing v0.4.0 as the most recent tag. :/

**Comment by sebv** [comment]
done, 1.0.0 is out btw
