### ISSUE TITLE
Custom promise chain method

### ISSUE THREAD

**Issue by JoeDawson** [admc/wd#414]
Hello,

I'm currently working on a custom chain method that's aim is to get an input, from a label's containing text.

Here's what I currently have:

```js
wd.addPromiseChainMethod(
	'inputFromLabel',
	function(text) {
		this
			.elementByXPath("//label[contains(., '" + text + "')]")
			.getAttribute('for', function(err, value) {
				return this.elementById(value);
			});
	}
);
```

Of which I call like so:

```js
it.only('allows submission', function(done) {
	this.page
		.inputFromLabel('SIA License Number').type('entry')
		.nodeify(done);
});
```

Which is unfortunately returning the following error:

> Error: [type("entry")] Error response status: 10, StaleElementReference - An element command failed because the referenced element is no longer attached to the DOM. Selenium error: stale element reference: element is not attached to the page document

I have debugged the majority of this but am stuck on getting past the `getAttribute()` as there isn't much documentation about it.

To further explain how I want this to work, I want it to do the following steps

- Fetch the label from the given text (working)
- Get the `for` attribute from the label (working)
- Get the input from this `for` value using the ID (not working)
- Return that input to allow for further chaining (in this case, the `type()` method)

Can you help?

**Comment by JoeDawson** [comment]
And here's an example of my HTML, of which is dynamic - hence why I am choosing to get an input like this.

```html
<label for='input_6_36' >SIA License Number</label>
<input name='input_36' id='input_6_36' type='text' />
```

**Comment by sebv** [comment]
You didn't return the promise in the custom method.

**Comment by JoeDawson** [comment]
Oops, missed that - still receiving the same error though.

```js
wd.addPromiseChainMethod(
	'inputFromLabel',
	function(text) {
		return this
			.elementByXPath("//label[contains(., '" + text + "')]")
			.getAttribute('for', function(err, value) {
				return this.elementById(value);
			});
	}
);
```

Any other ideas @sebv?

**Comment by sebv** [comment]
`function(err, value) {` has nothing to do in promise code.

**Comment by JoeDawson** [comment]
Then how can I do as I have mentioned above? There doesn't seem to be any examples or extensive documentation about this.

**Comment by sebv** [comment]
google "promise tutorial"

**Comment by JoeDawson** [comment]
Will look elsewhere for help :)
