### ISSUE TITLE
How to scroll and find an element in Android

### ISSUE THREAD

**Issue by prolificcoder** [admc/wd#418]
All my android elements are not currently visible, I am trying to come up with a generic method to scroll and find and element. What I have currently below doesn't work, appreciate idas
```
.elementByIdOrNull('elementId')
        .then(function(err,el){
          if(el==null){
              var action = new wd.TouchAction(driver)
                .moveTo({x: 20, y: 20}); // what should the the correct method and args to move the screen down?
              action.perform();
          }
          return driver.click() //perform click regardless
        })
```

**Comment by Kignuf** [comment]
Hello,

I also bumped into this problem a while ago, here is how I solved it. Hope that helps.

```
function scrollToElement(name) {
	return driver.elementByName(name)
		.then(function(el){
			Q.all([el.getLocation(), el.getSize()])
			.then(function(results){
				var loc = results[0];
				var size = results[1];
				return driver.swipe({
					startX: size.width/2,
					startY: loc.y + size.height/2,
					endX: size.width/2,
					endY: loc.y/2,
					duration: 700
				});
			});
		}).sleep(500);
}
```

**Comment by prolificcoder** [comment]
This may help me. Thank @Kignuf but how do you use this in wd promise chain? I am unable to use it correctly I tried the following method
```
.elementByIdOrNull(screens.domainScreen.placeBid)
         .then(function(el){
            if(el==null){
             return helpers.scrollToElementById(driver,screens.domainScreen.placeBid);
           }
           else return el;
         })
```

**Comment by Kignuf** [comment]
Hello, so sorry for the late answer !

I have the above function saved into a "gestures.js" file. Then in my main file, I do the following

```
var actions = require('./gestures');
wd.addPromiseChainMethod('swipe', actions.swipe);
chai.use(chaiAsPromised);
chai.should();
chaiAsPromised.transferPromiseness = wd.transferPromiseness;
driver = wd.promiseChainRemote(url, port);
```

I've setup all this a while ago and I believe most of it comes from the samples, so I honestly don't remember what each line is doing exactly.

**Comment by azaslavsky** [comment]
@Kignuf, what version of appium are you using?  Is this on 1.4.x?

**Comment by Kignuf** [comment]
I set it up on 1.4.x but upgraded to 1.5 soon after it was released and it's still working fine.

**Comment by azaslavsky** [comment]
Strange - at least on iOS, reverting to 1.4.16 solved the scroll issues.  There were mentions in the release docs of 1.5 conforming more closely to the native gesture APIs, which I guess do gestures based on relative rather than absolute coordinates.  Seems like the JS client still hasn't been updated to reflect that, so its odd that it works for you.

**Comment by sebv** [comment]
please use the  Appium issue list.
