### ISSUE TITLE
Unable to return a specific element from array (elementsBy..) and then tap it

### ISSUE THREAD

**Issue by Kignuf** [admc/wd#419]
Hello,

I have a script that uses elementsByName method. Then I want to filter the array and return the one item in the array that I'm interested in. Finally I simply tap that element.

Summary:
1. find all elements with corresponding name (using elementsByName)
2. find the one that is a UIAStaticText
3. return it
4. tap it

And the corresponding code:

```
return this.driver.elementsByName(getNameFromKey(key))
    .then(iosFilterStaticText).tap();

function iosFilterStaticText(elements) {
    var authorized = ['UIAStaticText'];
    elements.forEach(function(el){
        el.getTagName().then(function(tag){
            if(authorized.indexOf(tag) >= 0) {
                console.log(tag);
                console.log(el);
                return el;
            }
        });
    });
}
```

Unfortunately, this doesn't work. I get the following error (webdriver side):
>Error: Invalid method tap

As far as I understand, the problem is that I return undefined instead of the Static text.

Strangely, if I simply hardcode it and return as follow, it will work just fine:

```
function iosFilterStaticText(elements) {
    return elements[1];
}
```

There must be something wrong which makes my code fail to return "el" as expected, but I'm unable to find the error.

Any help would be greatly appreciated. Thanks !

ps: It might look weird to first find element by name and then apply a 2nd criteria, but there are reasons behind it, one of them being the fact that I'm using localization files to get the name, which will make my tests work on all languages.

**Comment by sebv** [comment]
Indeed promises do not work like this. Please refer to Q promise or Bluebird promise documentation.
