### ISSUE TITLE
Is there any library which could be used for taking snapshot(by dom element) and work well with WD.js?

### ISSUE THREAD

**Issue by IssacH** [admc/wd#427]
I am new to WD.js, just wanna to know if  there is any library which could be used for taking snapshot(by dom element) and work well with WD.js?

**Comment by sipayRT** [comment]
[gemini](https://github.com/gemini-testing/gemini)?

**Comment by sebv** [comment]
This is a driver, you wan't to check the server side (selenium and appium)
