### ISSUE TITLE
How to Abort/Cancel waitForConditionInBrowser?

### ISSUE THREAD

**Issue by flexpert** [admc/wd#428]
Hi all,

Is there anything I can do to abort/cancel a `waitForConditionInBrowser` request when I need to close the browser? 

The thing is I embedded `webdriver.waitForConditionInBrowser` into Node.js socket and I need to close the browser when socket disconnected, now, even if I call `webdriver.close()` I'm still getting the response  from `waitForConditionInBrowser`.

Thanks

**Comment by sebv** [comment]
U can probably build it within your condition, and execute another javascript to make it fail, or come back more regularly to the server.
