### ISSUE TITLE
swipe and wd

### ISSUE THREAD

**Issue by ndimer** [admc/wd#430]
Hi,

"swipe" action workaround for Appium doesn't seem to be working anymore. The following example won't work anymore:
```javascript
driver.execute("mobile: swipe", { "touchCount": 1, "startX": 360, "startY": 1087, "endX": 349, "endY": 631, "duration": 0.665 })
```

Gets error depreciation error from Appium server. Is there any way to do swipe using wd?

Thanks,
Nick

**Comment by sebv** [comment]
Please use appium issue board.
