### ISSUE TITLE
upgrade archiver and request modules

### ISSUE THREAD

**Issue by boneskull** [admc/wd#434]
Both of these modules have dependencies with known vulerabilities:

- [request@2.55.0 > hawk@2.3.1](https://nodesecurity.io/advisories/77)
- [archiver@0.14.4 > glob@4.3.5 > minimatch@2.0.10](https://nodesecurity.io/advisories/118)

PR #431 addresses the latter.

#433 is a problem, since it's unclear if PRs addressing either of these are OK.

**Comment by sebv** [comment]
upgraded in 1.0.0
