### ISSUE TITLE
Unable to get the set context in the appium and it showing error as 

### ISSUE THREAD

**Issue by ShibiKP** [admc/wd#438]
Contexts = 'mkConstants.AppDriver.Contexts' threw an exception of type 'System.InvalidOperationException' when using in c#
contexts as :- 
base = {"An unknown server-side error occurred while processing the command. (Original error: connect ECONNREFUSED)"}
Locations as :-
base = {"Not yet implemented. Please help us: http://appium.io/get-involved.html"}

**Comment by sebv** [comment]
Please use Appium issue list.
