### ISSUE TITLE
Question: what are the breaking changes between version 1.0.0 and 0.3.12 ?

### ISSUE THREAD

**Issue by georgehdd** [admc/wd#451]
Hi,

Do you have a document with the breaking changes between 0.3.12 and 1.0.0 ?

Thanks,

**Comment by sebv** [comment]
there is a release note

**Comment by georgehdd** [comment]
I read the release note, It's quite short. I asked regarding breaking changes.

> 1.0.0
>    upgraded all dependencies
>    code fixes for new dependencies
>    NodeJS v6 targeted version, tested against v5 in CI

**Comment by sebv** [comment]
If you use an old version of node (< v5), don't use the new version, otherwise you should be OK.
