### ISSUE TITLE
Unexpected data in simpleCallback - iOS Mobile ReactNative App

### ISSUE THREAD

**Issue by appiumams** [admc/wd#478]
OS :- IOS
Mobile IOS Application
Using React native and appium

When I try to run my cucumber-TS tests for a react native mobile app using appium, the simulator is launched, but I get an error before the application is launched.
Could you please help me?

Please find the error log below.
Error :- 
Step: Given the app is loaded - cucumber/features/ios_menu.feature:26
   Step Definition: node_modules/cucumber-tsflow/src/BindingDecorator.ts:157
   Message:
     **Error: [closeApp()] Unexpected data in simpleCallback.**
         at exports.newError (SOME_PATH/node_modules/wd/lib/utils.js:145:13)
         at SOME_PATH/node_modules/wd/lib/callbacks.js:42:12
         at SOME_PATHnode_modules/wd/lib/webdriver.js:179:5
         at Request._callback (SOME_PATH/node_modules/wd/lib/http-utils.js:88:7)
         at Request.self.callback (SOME_PATH/node_modules/wd/node_modules/request/request.js:186:22)
         at emitTwo (events.js:106:13)
         at Request.emit (events.js:192:7)
         at Request.<anonymous> (SOME_PATH/node_modules/wd/node_modules/request/request.js:1081:10)
         at emitOne (events.js:96:13)
         at Request.emit (events.js:189:7)

Appium log:- 
yarn appium v0.23.4
$ "SOME_PATH/node_modules/.bin/appium" 
[Appium] Welcome to Appium v1.6.5 (REV a1b9e39a928b543fb3e4dba2437666087c662621)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
[HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"automationName":"XCUITest","platformName":"iOS","deviceName":"iPhone 6","app":"ios/_build/Build/Products/Release-iphonesimulator/SOME_APP.app","noReset":true}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"automationName":"XCUITest","platformName":"iOS","deviceName":"iPhone 6","app":"ios/_build/Build/Products/Release-iphonesimulator/SOME_APP.app","noReset":true},null,null]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1498047515256 (13:18:35 GMT+0100 (BST))
[Appium] Creating new XCUITestDriver (v2.30.0) session
[Appium] Capabilities:
[Appium]   automationName: 'XCUITest'
[Appium]   platformName: 'iOS'
[Appium]   deviceName: 'iPhone 6'
[Appium]   app: 'ios/_build/Build/Products/Release-iphonesimulator/SOME_APP.app'
[Appium]   noReset: true
[debug] [XCUITest] XCUITestDriver version: 2.30.0
[BaseDriver] Session created with session id: dcb0ef8c-97eb-42d0-9c8c-b63841c4bb09
[HTTP] --> POST /wd/hub/session/appium/app/close {}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /wd/hub/session/appium/app/close 404 6 ms - 74 
[HTTP] --> POST /wd/hub/session/appium/app/close {}
[debug] [HTTP] No route found. Setting content type to 'text/plain'
[HTTP] <-- POST /wd/hub/session/appium/app/close 404 1 ms - 74 
[HTTP] <-- POST /wd/hub/session - - ms - - 
[debug] [XCUITest] Xcode version set to '8.3.2' (tools v8.3.2.0.1.1492020469)
[debug] [XCUITest] iOS SDK Version set to '10.3'
[debug] [BaseDriver] Event 'xcodeDetailsRetrieved' logged at 1498047515697 (13:18:35 GMT+0100 (BST))
[XCUITest] Simulator udid not provided, using desired caps to create a new simulator
[XCUITest] No platformVersion specified. Using latest version Xcode supports: '10.3' This may cause problems if a simulator does not exist for this platform version.
[iOSSim] Constructing iOS simulator for Xcode version 8.3.2 with udid '070C7A8C-5FBE-4D8A-8579-C3B3FAB47D7F'
[XCUITest] Created simulator with udid '070C7A8C-5FBE-4D8A-8579-C3B3FAB47D7F'.
[XCUITest] Determining device to run tests on: udid: '070C7A8C-5FBE-4D8A-8579-C3B3FAB47D7F', real device: false
[BaseDriver] Using local app 'ios/_build/Build/Products/Release-iphonesimulator/SOME_APP.app'
[debug] [BaseDriver] Event 'appConfigured' logged at 1498047516474 (13:18:36 GMT+0100 (BST))
[debug] [XCUITest] Checking whether app 'ios/_build/Build/Products/Release-iphonesimulator/SOME_APP.app' is actually present on file system
[debug] [XCUITest] App is present
[debug] [iOS] Getting bundle ID from app 'ios/_build/Build/Products/Release-iphonesimulator/SOME_APP.app': 'com.abc.com'
[debug] [BaseDriver] Event 'resetStarted' logged at 1498047516483 (13:18:36 GMT+0100 (BST))
[debug] [XCUITest] Reset: noReset is on. Leaving simulator as is
[debug] [BaseDriver] Event 'resetComplete' logged at 1498047516484 (13:18:36 GMT+0100 (BST))
[debug] [iOSLog] Starting iOS 10.3 simulator log capture
[debug] [iOSLog] System log path: SOME_PATH/Library/Logs/CoreSimulator/070C7A8C-5FBE-4D8A-8579-C3B3FAB47D7F/system.log
[debug] [BaseDriver] Event 'logCaptureStarted' logged at 1498047516649 (13:18:36 GMT+0100 (BST))
[XCUITest] Setting up simulator
[debug] [iOS] No reason to set locale
[debug] [iOS] No iOS / app preferences to set
[XCUITest] Simulator with udid '070C7A8C-5FBE-4D8A-8579-C3B3FAB47D7F' not booted. Booting up now
[debug] [iOSSim] Killing all iOS Simulators
[debug] [iOSSim] Using fkill to kill processes: 40339
[iOSSim] Starting simulator with command: open -Fn /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 070C7A8C-5FBE-4D8A-8579-C3B3FAB47D7F -ConnectHardwareKeyboard 0
[debug] [XCUITest] Installing ios/_build/Build/Products/Release-iphonesimulator/SOME_APP.app on Simulator with UUID '070C7A8C-5FBE-4D8A-8579-C3B3FAB47D7F'...
[iOSSim] Simulator booted in 24514ms
[debug] [BaseDriver] Event 'simStarted' logged at 1498047552868 (13:19:12 GMT+0100 (BST))
[debug] [XCUITest] The app has been installed successfully.
[debug] [BaseDriver] Event 'appInstalled' logged at 1498047559635 (13:19:19 GMT+0100 (BST))
[debug] [BaseDriver] Event 'wdaStartAttempted' logged at 1498047559637 (13:19:19 GMT+0100 (BST))
[XCUITest] Using WDA path: 'SOME_PATH/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[XCUITest] Using WDA agent: 'SOME_PATH/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj'
[XCUITest] Launching WebDriverAgent on the device
[debug] [XCUITest] Carthage found: '/usr/local/bin/carthage'
[debug] [XCUITest] Running WebDriverAgent bootstrap script to install dependencies
[debug] [XCUITest] Creating WebDriverAgent resources directory
[debug] [XCUITest] Creating WebDriverAgent resource bundle directory
[debug] [XCUITest] Killing hanging processes
[debug] [XCUITest] Beginning test with command 'xcodebuild build-for-testing test-without-building -project SOME_PATH/MAIN/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=070C7A8C-5FBE-4D8A-8579-C3B3FAB47D7F -configuration Debug IPHONEOS_DEPLOYMENT_TARGET=10.3' in directory 'SOME_PATH/node_modules/appium/node_modules/appium-xcuitest-driver/WebDriverAgent'
[debug] [XCUITest] Output from xcodebuild will not be logged
[debug] [XCUITest] Waiting up to 60000ms for WebDriverAgent to start
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [XCUITest] Log file for xcodebuild test: SOME_PATH/Library/Developer/Xcode/DerivedData/WebDriverAgent-dwexxylbraexfiexmxwcjczugrpd/Logs/Test/8C87EAFF-EBA0-47E6-ACEF-C7ACBC032262/Session-WebDriverAgentRunner-2017-06-21_131936-HlvE8n.log
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:8100/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n    \"state\" : \"success\",\n    \"os\" : {\n      \"name\" : \"iOS\",\n      \"version\" : \"10.3\"\n    },\n    \"ios\" : {\n      \"simulatorVersion\" : \"10.3\",\n      \"ip\" : \"10.8.0.41\"\n    },\n    \"build\" : {\n      \"time\" : \"Jun 21 2017 13:19:34\"\n    }\n  },\n  \"sessionId\" : \"BE7BD8B6-1D19-42B1-AA97-9C94FA7286DE\",\n  \"status\" : 0\n}"
[debug] [XCUITest] WebDriverAgent running on ip '10.8.0.41'
[debug] [XCUITest] WebDriverAgent successfully started after 19331ms
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1498047583889 (13:19:43 GMT+0100 (BST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.abc.com","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Application is not running, possibly crashed","sessionId":"54FD903E-5378-4F6B-8D8E-58C6CFFF6492","status":10}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1498047596180 (13:19:56 GMT+0100 (BST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.abc.com","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Application is not running, possibly crashed","sessionId":"DE3A5ABA-0E7D-432D-94FC-E9F90191DCCD","status":10}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1498047607495 (13:20:07 GMT+0100 (BST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.abc.com","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Application is not running, possibly crashed","sessionId":"819CC312-CE7A-4799-842C-279C94882D37","status":10}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1498047619241 (13:20:19 GMT+0100 (BST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.abc.com","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Application is not running, possibly crashed","sessionId":"EC90B0E4-611E-4AE4-8D03-42135287A460","status":10}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1498047630509 (13:20:30 GMT+0100 (BST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.abc.com","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Application is not running, possibly crashed","sessionId":"0044CF0D-98C1-4D32-B4A0-132588443713","status":10}
[debug] [XCUITest] Failed to create WDA session. Retrying...
[debug] [BaseDriver] Event 'wdaSessionAttempted' logged at 1498047642204 (13:20:42 GMT+0100 (BST))
[debug] [XCUITest] Sending createSession command to WDA
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:8100/session] with body: {"desiredCapabilities":{"bundleId":"com.abc.com","arguments":[],"environment":{},"shouldWaitForQuiescence":true,"shouldUseTestManagerForVisibilityDetection":false,"maxTypingFrequency":60,"shouldUseSingletonTestManager":true}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{"sessionId":"C805D404-095F-4B64-A1D1-48D0CF891E71","capabilities":{"device":"iphone","browserName":" ","sdkVersion":"10.3","CFBundleIdentifier":"local.pid.42399"}},"sessionId":"C805D404-095F-4B64-A1D1-48D0CF891E71","status":0}
[debug] [BaseDriver] Event 'wdaSessionStarted' logged at 1498047644493 (13:20:44 GMT+0100 (BST))
[debug] [XCUITest] Found WDA derived data folder: 'SOME_PATH/Library/Developer/Xcode/DerivedData/WebDriverAgent-asorlvakbhkvgefvbhiaimkazygb'
[XCUITest] Setting '555' permissions to 'SOME_PATH/Library/Developer/Xcode/DerivedData/WebDriverAgent-asorlvakbhkvgefvbhiaimkazygb/Logs/Test/Attachments' folder
[debug] [XCUITest] Found WDA derived data folder: 'SOME_PATH/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn'
[debug] [XCUITest] Found WDA derived data folder: 'SOME_PATH/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceehwuohbvcomzgspujxsamwbiad'
[XCUITest] Setting '555' permissions to 'SOME_PATH/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceehwuohbvcomzgspujxsamwbiad/Logs/Test/Attachments' folder
[debug] [XCUITest] Found WDA derived data folder: 'SOME_PATH/Library/Developer/Xcode/DerivedData/WebDriverAgent-dmyzvsvbniixpygnpboprjuymgmz'
[XCUITest] Setting '555' permissions to 'SOME_PATH/Library/Developer/Xcode/DerivedData/WebDriverAgent-dmyzvsvbniixpygnpboprjuymgmz/Logs/Test/Attachments' folder
[debug] [XCUITest] Found WDA derived data folder: 'SOME_PATH/Library/Developer/Xcode/DerivedData/WebDriverAgent-dwexxylbraexfiexmxwcjczugrpd'
[XCUITest] Setting '555' permissions to 'SOME_PATH/Library/Developer/Xcode/DerivedData/WebDriverAgent-dwexxylbraexfiexmxwcjczugrpd/Logs/Test/Attachments' folder
[debug] [BaseDriver] Event 'wdaPermsAdjusted' logged at 1498047644506 (13:20:44 GMT+0100 (BST))
[debug] [BaseDriver] Event 'wdaStarted' logged at 1498047644507 (13:20:44 GMT+0100 (BST))
[debug] [XCUITest] Setting initial orientation to 'PORTRAIT'
[debug] [JSONWP Proxy] Proxying [POST /orientation] to [POST http://localhost:8100/session/C805D404-095F-4B64-A1D1-48D0CF891E71/orientation] with body: {"orientation":"PORTRAIT"}
[debug] [JSONWP Proxy] Got response with status 200: {"value":{},"sessionId":"C805D404-095F-4B64-A1D1-48D0CF891E71","status":0}
[debug] [BaseDriver] Event 'orientationSet' logged at 1498047644796 (13:20:44 GMT+0100 (BST))
[Appium] New XCUITestDriver session created successfully, session dcb0ef8c-97eb-42d0-9c8c-b63841c4bb09 added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1498047644798 (13:20:44 GMT+0100 (BST))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"automationName":"XCUITest","platformName":"iOS","deviceName":"iPhone 6","app":"ios/_build/Build/Products/Release-iphonesimulator/SOME_APP.app","noReset":true,"udid":"070C7A8C-5FBE-4D8A-8579-C3B3FAB47D7F"}
[BaseDriver] Shutting down because we waited 60 seconds for a command
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session dcb0ef8c-97eb-42d0-9c8c-b63841c4bb09 from our master session list
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down xcodebuild process (pid 42638)
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[debug] [XCUITest] Found WDA derived data folder: 'SOME_PATH/Library/Developer/Xcode/DerivedData/WebDriverAgent-asorlvakbhkvgefvbhiaimkazygb'
[XCUITest] Setting '755' permissions to 'SOME_PATH/Library/Developer/Xcode/DerivedData/WebDriverAgent-asorlvakbhkvgefvbhiaimkazygb/Logs/Test/Attachments' folder
[debug] [XCUITest] Found WDA derived data folder: 'SOME_PATH/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceakatlydgitcjebccsbdhchgrpn'
[debug] [XCUITest] Found WDA derived data folder: 'SOME_PATH/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceehwuohbvcomzgspujxsamwbiad'
[XCUITest] Setting '755' permissions to '/Users/msuiwintest/Library/Developer/Xcode/DerivedData/WebDriverAgent-ceehwuohbvcomzgspujxsamwbiad/Logs/Test/Attachments' folder
[debug] [XCUITest] Found WDA derived data folder: 'SOME_PATH/Library/Developer/Xcode/DerivedData/WebDriverAgent-dmyzvsvbniixpygnpboprjuymgmz'
[XCUITest] Setting '755' permissions to 'SOME_PATH/Library/Developer/Xcode/DerivedData/WebDriverAgent-dmyzvsvbniixpygnpboprjuymgmz/Logs/Test/Attachments' folder
[debug] [XCUITest] Found WDA derived data folder: 'SOME_PATH/Library/Developer/Xcode/DerivedData/WebDriverAgent-dwexxylbraexfiexmxwcjczugrpd'
[XCUITest] Setting '755' permissions to 'SOME_PATH/Library/Developer/Xcode/DerivedData/WebDriverAgent-dwexxylbraexfiexmxwcjczugrpd/Logs/Test/Attachments' folder
[debug] [XCUITest] Not clearing log files. Use `clearSystemFiles` capability to turn on.
[debug] [iOSLog] Stopping iOS log capture

**Comment by imurchie** [comment]
This can be any number of things, and unfortunately `wd` masks the actual return value. The easiest way to get to the bottom of it is to look in the stack trace:
```
Error: [closeApp()] Unexpected data in simpleCallback.
  at exports.newError (SOME_PATH/node_modules/wd/lib/utils.js:145:13)
  at SOME_PATH/node_modules/wd/lib/callbacks.js:42:12
  at SOME_PATHnode_modules/wd/lib/webdriver.js:179:5
  at Request._callback (SOME_PATH/node_modules/wd/lib/http-utils.js:88:7)
  at Request.self.callback 
  (SOME_PATH/node_modules/wd/node_modules/request/request.js:186:22)
  at emitTwo (events.js:106:13)
  at Request.emit (events.js:192:7)
  at Request. (SOME_PATH/node_modules/wd/node_modules/request/request.js:1081:10) 
  at emitOne (events.js:96:13)
  at Request.emit (events.js:189:7)
```
And then add some logging before the error is thrown (generally, in here: https://github.com/admc/wd/blob/master/lib/callbacks.js#L9-L47)

**Comment by appiumams** [comment]
Thanks for your quick response @imurchie i will update you soon once i find the root cause.

**Comment by appiumams** [comment]
Hi @imurchie , I rebuild my project and node modules and i no longer had that error.
You can close this defect.
Thanks again for your quick response.

**Comment by imurchie** [comment]
I think you have to close it. I can't.

But I'm glad things were resolved!
