### ISSUE TITLE
Relationship with webdriverio?

### ISSUE THREAD

**Issue by ben-yip** [admc/wd#543]
Hello, 
I'm new to Appium and have trouble deciding which js binding client to use...
I read [this issue](https://github.com/admc/wd/issues/416) about the merging plan with webdriverio in late 2015, but currently I find both repo are updating actively. 
It seems to me that the 2 repo are vibrant and independent.
So, may I again ask about the future plan?

**Comment by jlipps** [comment]
Definitely use webdriverio. It is _much_ better maintained at the moment. The merge is still a good idea but there's no active work being done on it. If you're just starting out, pick webdriverio.
