### ISSUE TITLE
Update request dependency

### ISSUE THREAD

**Issue by davedoesdev** [admc/wd#555]
github is moaning about a vuln in cryptiles@3.12, brought in via request.

**Comment by admc** [comment]
Github has outlined a whole slew of vulnerabilities in outdated package
dependencies. Much of this requires pretty significant changes, which will
take some free weekends!

**Comment by davedoesdev** [comment]
No problem - library is still working great (thanks)!
For non-production use this won't be relevant anyway.

**Comment by kt3k** [comment]
cryptiles seems required like this way:
```
  └─┬ wd@1.10.3
    └─┬ request@2.85.0
      └─┬ hawk@6.0.2
        └── cryptiles@3.1.2 
```

`request` module seems to have dropped hawk dependency lately (ref: https://github.com/request/request/pull/2943 )

If we update `request` dependency version to 2.87 or above, the above vulnerability warning should disappear.

**Comment by mattrayner** [comment]
@admc is this something you would accept a PR for? I'm more than happy to have a go

**Comment by admc** [comment]
@mattrayner absolutely, I really want to update all this stuff, but I simply can't find the time right now! If you are willing to send some PR's over, I will absolutely review, test and merge.

**Comment by mattrayner** [comment]
@admc Amazing, I'll have a go right now1

**Comment by admc** [comment]
Working on it.

**Comment by NozomiIto** [comment]
Thank you so much!

**Comment by jonny-improbable** [comment]
Hi @admc, thanks for looking into this issue

I can't see a new version of wd on npm. The latest version of the [wd package](https://www.npmjs.com/package/wd) at the time of this comment is 1.11.1 which was released 2 months ago,

<img width="792" alt="screenshot 2019-01-12 at 16 31 19" src="https://user-images.githubusercontent.com/14162673/51075724-83414680-1687-11e9-8d57-e7030dac23da.png">

I don't feel that this issue should be closed until a new version (1.11.2) is published to npm. Apologies if I've misunderstood anything.

**Comment by NozomiIto** [comment]
I think 1.11.1 contains the fix for this problem, and it actually resolved this issue on my environment.

**Comment by admc** [comment]
@jonny-improbable can you check it out and let me know if your issue is solved?
