### ISSUE TITLE
elementByImage works for simpler images

### ISSUE THREAD

**Issue by zbranzov** [admc/wd#558]
Hi, 
elementByImage is a great new feature but it seems a bit unreliable yet. In some cases, it does find my image on the screen but only for very simple images. If I use for example a more complex one it won't. A real example is this image https://screencast.com/t/K9GGCPZ7Q that does not get matched on the screen but if I look only for the 'blue square' it does. So I wonder if there is a way to get the device screenshot and try to find why it does not match with my reference image? Now I have only the reference image and can't get further.

**Comment by jlipps** [comment]
Hi there, thanks for the report. It does seem you've run into a legitimate issue, however it has to do with the behavior of the Appium server and not this library. Please report it at https://github.com/appium/appium/issues!
