### ISSUE TITLE
It didn't applied critical typo issue at v1.11.0

### ISSUE THREAD

**Issue by boxersb** [admc/wd#567]
I've found an issue below, while building a test automation environment using selenium.

<img width="674" alt="screen shot 2018-11-26 at 6 02 52 pm" src="https://user-images.githubusercontent.com/189953/49003655-b9913800-f1a5-11e8-892c-c9a6982633b7.png">

And, I found this commit either.
> https://github.com/admc/wd/commit/b9678b7602b738ac2906aa4dbd2bac60f861d878

But, there is no effect on `v1.11.0` what your latest release.  

I think, a new hotfix is expected to be released soon.

**Comment by khanhdodang** [comment]
@boxersb I see it has already released. I use version `1.11.2`. I think you can close this ticket now.
