### ISSUE TITLE
Unexpected end of JSON input while parsing near '...","dependencies":{"ba'

### ISSUE THREAD

**Issue by queenie0708** [admc/wd#569]
Got
"Unexpected end of JSON input while parsing near '...","dependencies":{"ba'"
When "npm install -g wd"

**Comment by admc** [comment]
Can you remove and try again? That looks like an incomplete network request or something.

Here's what it looked like for me, maybe you can paste the rest of the output?

adam@langara:~$ npm install -g wd
/usr/local/bin/wd -> /usr/local/lib/node_modules/wd/lib/bin.js

> wd@1.11.1 install /usr/local/lib/node_modules/wd
> node scripts/build-browser-scripts

+ wd@1.11.1
added 2 packages from 3 contributors and updated 92 packages in 5.849s
