### ISSUE TITLE
Release 1.11.3

### ISSUE THREAD

**Issue by gabegorelick** [admc/wd#595]
It would be nice if you could release a version that includes https://github.com/admc/wd/pull/591. Newer versions of lodash address a few high severity issues (https://github.com/lodash/lodash/issues/4348).

**Comment by admc** [comment]
@imurchie @jlipps thoughts?

**Comment by gabegorelick** [comment]
Any progress on this?

**Comment by raymondtang310** [comment]
I would also like for this issue to be addressed. Running `yarn audit` / `npm audit` on my app which uses wd tells me that there is a high severity vulnerability with lodash.

**Comment by jlipps** [comment]
v1.11.3 has been released
