### ISSUE TITLE
Getting 'npm ERR! Cannot read properties of null (reading 'pickAlgorithm')' when running `npm install wd`

### ISSUE THREAD

**Issue by tking16** [admc/wd#635]
Only happens on our Macmini which is used to run CI tests. Judging by the error it seems because 'request' is deprecated? But I don't know what to about that as wd seems to be trying to install it anyway

more info:
```
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! Cannot read properties of null (reading 'pickAlgorithm')
```

What I've tried so far
running `npm cache clear --force` didn't work
upgrading both npm and node - didn't help

Node version: v18.7.0
npm version: 8.15.0

full npm error logs

[error log](https://gist.github.com/tking16/d5d0ebbae8285cb2f0b166bc88c77c16)

Thanks for any advice

**Comment by admc** [comment]
Hi @tking16 sorry to hear you're having trouble. WD is a very deprecated project at this point, I really suggest you check out webdriver.io. If you really need to get this working, I suggest you try with older versions of node and npm. If you want to dig in and migrate the codebase to newer packages to help others in your position, I would certainly be interested in merging that work.
