### ISSUE TITLE
Request has been deprecated and is raising security vulnerabilities

### ISSUE THREAD

**Issue by zacmoss-jaspar** [admc/wd#640]
I've run `npm audit` on my repo where wd is a transitive dependency.

# Expected outcome

No security vulnerabilities.

# Actual outcome
```
request  *
Severity: moderate
Server-Side Request Forgery in Request - https://github.com/advisories/GHSA-p8p7-x288-28g6

wd  >=0.0.27
Depends on vulnerable versions of request
node_modules/wd
```

# Suggestion
Find replacement package for `request`

**Comment by jlipps** [comment]
Sorry, this project is no longer active or supported. Use webdriverio instead.
